# Generated by Django 5.2.8 on 2025-11-10 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('series_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('series_number', models.BigIntegerField()),
                ('series_production_date', models.DateField()),
                ('series_expire_date', models.DateField()),
            ],
            options={
                'db_table': 'series',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=20)),
                ('client_email', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'clients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoatingTypes',
            fields=[
                ('coating_types_id', models.AutoField(primary_key=True, serialize=False)),
                ('coating_type_name', models.CharField(max_length=40)),
                ('coating_type_nomenclatura', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'coating_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orders_id', models.AutoField(primary_key=True, serialize=False)),
                ('orders_status', models.CharField(max_length=30)),
                ('orders_created_at', models.DateField()),
                ('orders_shipped_at', models.DateField(blank=True, null=True)),
                ('orders_delivered_at', models.DateField(blank=True, null=True)),
                ('orders_cancel_reason', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdersItems',
            fields=[
                ('order_items_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_items_count', models.IntegerField()),
            ],
            options={
                'db_table': 'orders_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('order_status_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_status_history_from_stat', models.CharField(max_length=30)),
                ('order_status_history_to_status', models.CharField(max_length=30)),
                ('order_status_history_chang_at', models.CharField(max_length=30)),
                ('order_status_history_note', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'order_status_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.IntegerField()),
                ('product_name', models.CharField(max_length=40)),
                ('product_price', models.IntegerField()),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('stocks_id', models.AutoField(primary_key=True, serialize=False)),
                ('stocks_is_reserved_for_client', models.BooleanField()),
                ('stocks_update_at', models.DateField()),
                ('stocks_count', models.FloatField()),
            ],
            options={
                'db_table': 'stocks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.CharField(max_length=30)),
                ('user_password_hash', models.CharField(max_length=255)),
                ('user_is_active', models.BooleanField()),
                ('user_created_at', models.DateField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Analyses',
            fields=[
                ('series', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='prime_top.series')),
                ('analyses_blesk_pri_60_grad', models.FloatField(blank=True, null=True)),
                ('analyses_uslovnaya_vyazkost', models.FloatField(blank=True, null=True)),
                ('analyses_delta_e', models.FloatField(blank=True, null=True)),
                ('analyses_delta_l', models.FloatField(blank=True, null=True)),
                ('analyses_delta_a', models.FloatField(blank=True, null=True)),
                ('analyses_color_diff_deltae_d8', models.FloatField(blank=True, null=True)),
                ('analyses_delta_b', models.FloatField(blank=True, null=True)),
                ('analyses_vremya_sushki', models.FloatField(blank=True, null=True)),
                ('analyses_pikovaya_temperatura', models.FloatField(blank=True, null=True)),
                ('analyses_tolschina_dlya_grunta', models.FloatField(blank=True, null=True)),
                ('analyses_adgeziya', models.FloatField(blank=True, null=True)),
                ('analyses_stoikost_k_rastvor', models.FloatField(blank=True, null=True)),
                ('analyses_viz_kontrol_poverh', models.CharField(blank=True, max_length=15, null=True)),
                ('analyses_vneshnii_vid', models.CharField(blank=True, max_length=31, null=True)),
                ('analyses_kolvo_vykr_s_partii', models.FloatField(blank=True, null=True)),
                ('analyses_unnamed_16', models.FloatField(blank=True, null=True)),
                ('analyses_stepen_peretira', models.FloatField(blank=True, null=True)),
                ('analyses_tverd_vesches_po_v', models.FloatField(blank=True, null=True)),
                ('analyses_grunt', models.CharField(blank=True, max_length=30, null=True)),
                ('analyses_tolsch_plenki_zhidk', models.FloatField(blank=True, null=True)),
                ('analyses_tolsch_dly_em_lak_ch', models.FloatField(blank=True, null=True)),
                ('analyses_teoreticheskii_rashod', models.FloatField(blank=True, null=True)),
                ('analyses_prochnost_pri_izgibe', models.FloatField(blank=True, null=True)),
                ('analyses_stoikost_k_obrat_udaru', models.FloatField(blank=True, null=True)),
                ('analyses_tverdost_po_karandashu', models.CharField(blank=True, max_length=2, null=True)),
                ('analyses_prochn_rastyazh_po_er', models.FloatField(blank=True, null=True)),
                ('analyses_blesk', models.FloatField(blank=True, null=True)),
                ('analyses_plotnost', models.FloatField(blank=True, null=True)),
                ('analyses_mass_dolya_nelet_vesh', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analyses',
                'managed': False,
            },
        ),
    ]
