# Generated by ChatGPT on 2025-11-23
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prime_top', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tg_chat_id', models.BigIntegerField(unique=True)),
                ('tg_username', models.CharField(blank=True, max_length=255, null=True)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_status_sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_links', to='prime_top.users')),
            ],
            options={
                'db_table': 'telegram_links',
                'managed': True,
            },
        ),
    ]
